@startuml
    skinparam Shadowing false
    skinparam ParticipantPadding 20

    participant Selectable

    Selectable -> Selectable: SetHovered(value)
    note right: isHovered = value
    Selectable -> Selectable: RefreshVisual()

@enduml