@startuml
    skinparam Shadowing false
    skinparam ParticipantPadding 20

    participant Selectable
    participant Color

    opt renderers == null
        Selectable -> Selectable : return
        note right : exit method
    end

    loop for each r
        
    end


@enduml