@startuml
    skinparam Shadowing false
    skinparam ParticipantPadding 20

    participant Selectable

    Selectable -> Selectable : ToggleSelected()
    note right : isSelected = !isSelected
    Selectable -> Selectable : RefreshVisual()

@enduml