@startuml
    skinparam Shadowing false
    skinparam ParticipantPadding 20

    actor Player
    Participant SelectionManager
    Participant Input
    Participant selectionBoxUI
    Participant GetScreenRect

    opt เมาส์ซ้ายถูกกดค้าง
        SelectionManager -> Input : GetMouseButtonDown(0)
        Input --> SelectionManager :Return mousePosition
        SelectionManager -> SelectionManager : dragStart = mousePosition
        SelectionManager -> SelectionManager : dragging = true
        
        opt selectionBoxUI != null
            SelectionManager -> selectionBoxUI : Begin(dragStart)
        end
    end

    opt dragging == true && Input.GetMouseButton(0)
        opt selectionBoxUI != null
            SelectionManager -> Input : mousePosition
            Input --> SelectionManager : return mousePosition
            SelectionManager -> selectionBoxUI : Drag(mousePosition)
        end
    end

    opt dragging == true && Input.GetMouseButtonUp(0)
        SelectionManager -> SelectionManager : dragging = false
        SelectionManager -> Input : mousePosition
        Input --> SelectionManager : return mousePosition
        SelectionManager -> SelectionManager : end = (Vector2)mousePosition

        opt selectionBoxUI != null
            SelectionManager -> selectionBoxUI : End
        end

        SelectionManager -> GetScreenRect : (dragStart, end)
        GetScreenRect --> SelectionManager : return screenRect

        alt screenRect.size.magnitude > 10f
            SelectionManager -> SelectionManager : isBox = true
        else
            SelectionManager -> SelectionManager : isBox = false
        end
    
        alt Input.GetKey(KeyCode.LeftShift) || Input.GetKey(KeyCode.RightShift)
            SelectionManager -> SelectionManager : shift = true
        else
            SelectionManager -> SelectionManager : shift = false
        end

        alt Input.GetKey(KeyCode.LeftControl) || Input.GetKey(KeyCode.RightControl)
            SelectionManager -> SelectionManager : ctrl = true
        else
            SelectionManager -> SelectionManager : ctrl = false
        end

        opt ไม่กด shift และ ไม่กด ctrl
            SelectionManager -> SelectionManager : ClearSelection()
        end

        alt isBox == true
            SelectionManager -> SelectionManager : BoxSelect(screenRect, shift, ctrl)
        else
            SelectionManager -> SelectionManager : ClickSelect(shift,ctrl)
        end  
    end
@enduml