@startuml
    skinparam Shadowing false
    skinparam ParticipantPadding 20

    participant Selectable

    Selectable -> Selectable : get WorldCenter

    alt renderer != null and renderers.Length > 0
        note right: r = renderers[0]
    else
        Selectable -> Selectable : GetComponentInChildren<Renderer>
        note right: r = ผลลัพธ์จาก GetComponentInChildren
    end

    alt r != null
        Selectable -> Selectable : return r.bound.center
    else
        Selectable -> Selectable : return transform.position
    end

@enduml