@startuml
    skinparam Shadowing false
    skinparam ParticipantPadding 20

    participant EdgePanMenu
    participant Toggle

    opt edgePanToggle != null
        Toggle -> Toggle : RemoveListener(OnToggleChanged)
    end

@enduml