@startuml
    skinparam Shadowing false
    skinparam ParticipantPadding 20

    participant EdgePanMenu
    participant RtsCamera
    participant UnityEngine

    opt rtsCamera == null
        alt UNITY_2023_1_OR_NEWER
            EdgePanMenu -> UnityEngine : FindFirstObjectByType<RtsCamera>
            UnityEngine --> EdgePanMenu : RtsCamera instance
        else
            EdgePanMenu -> UnityEngine : FindObjectOfType<RtsCamera>
            UnityEngine --> EdgePanMenu : RtsCamera instance
        end
    end

@enduml