@startuml
    skinparam Shadowing false
    skinparam ParticipantPadding 20

    participant EdgePanMenu
    participant PlayerPrefs
    participant RtsCamera

    opt rtsCamera != null
        EdgePanMenu -> RtsCamera : SetEdgePan(isOn)
    end
    
    EdgePanMenu -> EdgePanMenu : result = isOn ? 1 : 0
    EdgePanMenu -> PlayerPrefs : SetInt(PrefKey, result)
    EdgePanMenu -> PlayerPrefs : Save()

@enduml