@startuml
    skinparam Shadowing false

    class URTS_GPT.CameraSystem.RtsCamera{
    .. Pan ..
    - panSpeed : float
    - edge : float
    - edgePan : bool

    .. Zoom ..
    - zoomSpeed : float
    - minY : float
    - maxY : float
    - zoomSmoothTime : float
    - invertScroll : bool

    .. Bounds ..
    - useBounds : bool
    - minXZ : Vector2
    - maxXZ : Vector2

    .. Smoothing ..
    - moveSmoothTime : float

    .. Reset ..
    - resetRotation : bool

    # moveVel : Vector3
    # zoomVel : float

    - startCameraPos : Vector3
    - startCameraRota : Quaternion

    + IsEdgePanEnabled : bool {readOnly}

    + SetEdgePan(enabled : bool) : void

    + Start() : void

    + Update() : void

    # OnDrawGizmosSelected() : void <<EditorOnly>>
    }
@enduml